### ISSUE TITLE
Missing stars or hr attribute from Bright Star Catalogue

### ISSUE THREAD

**Issue by rhannequin** [astronexus/HYG-Database#22] opened 2020-07-03 18:27 UTC
Hello,

First, thank you for this amazing work.

I noticed that there were only 8,912 stars in HYG database with magnitude <= 6.5, which is the [definition](https://en.wikipedia.org/wiki/Bright_Star_Catalogue) of the Bright Star Catalogue (BSC):
> star catalogue that lists all stars of stellar magnitude 6.5 or brighter

However, BSC contains 9,110 objects, of which 9,095 are stars, which could let think that 183 stars are missing in HYG database, or are actually in it but lack their `hr` parameter.

Is there a reason I was not able to find out to explain these missing stars?

I was not able to differenciate stars from other objects in BSC, but here is the list of stars ids from BSC that are not present in HYG database:

```
[
  1, 92, 95, 182, 231, 283, 545, 596, 604, 888, 898, 928, 1057, 1190, 1212, 1506, 1704, 1841, 1851, 1880, 1894,
  1932, 1949, 2176, 2322, 2341, 2357, 2358, 2366, 2472, 2485, 2496, 2814, 2843, 2871, 2910, 2949, 2950, 2980,
  3206, 3208, 3209, 3311, 3313, 3328, 3515, 3553, 3671, 3781, 3891, 4058, 4210, 4260, 4401, 4444, 4619, 4729,
  4731, 4764, 4822, 5034, 5211, 5343, 5386, 5476, 5478, 5506, 5606, 5789, 5834, 5852, 6026, 6106, 6113, 6186,
  6263, 6309, 6407, 6485, 6515, 6660, 6694, 6730, 6750, 6758, 6848, 7052, 7054, 7189, 7539, 7960, 8059, 8296,
  8559, 8793, 9075, 9090
]
```

I agree 183 out of 9,095 in BSC and out of 119,615 stars in HYG database is not a lot, but I still would like to know if these are actually missing or if there is an explaination.

Thank you.

**Comment by astronexus** [comment] 2023-09-15 16:52
I spot checked the first few of these and many, but not all. are problematic entries in the YBSC.

HR 1: this is HIP 424, so might be a true missing entry
HR 92: Same as SN 1572A, a supernova remnant. Not a HYG object (i.e., a visible star in one of the 3 source catalogs or one of its companions if multiple).
HR 95: Same as NGC 104, a globular cluster. Not a HYG object.
HR 182: Nova in M 31, the Andromeda Galaxy. Not a HYG object.
HR 231: 65 Psc A, lacks a HIPPARCOS ID, but is plausibly a true missing entry
HR 545: One component of Gamma Ari. The HR entry is not cross-referenced in HIP despite being a bright star. The HIP entry for this star is HIP 8832, which does not have an HR ID.

So at least for the first few cases, the issue is mostly (a) something with an HR number that doesn't belong in a star catalog or (b) something with an HR number that is not linked correctly to something with a HIP number.
  
This is something I will investigate in more detail for later versions of HYG and AT-HYG.

**Comment by astronexus** [comment] 2023-09-16 00:32
I've done a closer look at the first 10 entries in the list. A very common pattern is the following:

1) The star is part of a multiple star (usually a double).
2) The HIPPARCOS catalog ID for it is a single ID (i.e., the HIPPARCOS mission didn't split it into components)
3) There are 2 (or more) HR IDs, assigned to the components, separately.

In this case only 1 of the multiple HR IDs is recorded. An example:
 
HR 231 = 65 Psc A
HR 230 = 65 Psc B
HIP 4757 (only entry for this star) had to be assigned to only one HR ID, and HR 230 was chosen
HR 231 is missing

When there is only one HIP ID for a multiple star  the magnitude for HIP is the combined magnitude and the position effectively an average position of the entire star system. Trying to take HIP data for the combined system, and then using HR/Gliese/etc. data for one of the components to estimate the correct values for the other component was too error-prone to pursue reliably. So only the single HIP entry is kept. As a result, one of the two possible HR IDs (usually the higher one) is dropped.

I suspect this will account for most if not all of the remaining missing HR IDs that aren't associated with things like deep-sky objects and nova/supernova remnants (a few of which are already accounted for), but I will examine a larger sample before drawing firmer conclusions.

**Comment by rhannequin** [comment] 2023-09-18 18:51
This work and explanation is already largely appreciated, thank you for investigating and maintaining the repository.

**Comment by astronexus** [comment] 2023-09-24 17:55
I have taken a look (via SIMBAD) at the HR IDs listed in the original report.

As expected most (68 of 98) were cases where a multiple star had HR IDs assigned to the components but the HIP entry was for the combined brightness and average position, leading to one of the HR IDs being dropped. As I noted above, this is by design, so these cases won't be handled further.

Similarly, there are 14 objects in the YBSC that are out of scope for HYG, being either non-stellar objects or extremely faint nova or supernova remnants.

That leaves 16 IDs left to review. Of these, 4 exist in HYG but without the HR ID, most likely a result of accidentally omitting those IDs long ago in the original compilation. There will be a small update soon to add these 4 IDs.

The remaining 12 HR stars (HR 1704, 2322, 2341, 2366, 2950, 3328, 4210, 5343, 6263, 6660, 6848, 9090) are genuinely missing from HIP. Adding them will be a bit more involved since they aren't in HIP, only YBSC. Also, once added, most of the useful auxiliary information (like distances and proper motions) will be of lower quality than the data from HIP.

**Comment by astronexus** [comment] 2023-09-26 06:17
I have added these 16 IDs (4 HR IDs to existing HIP stars, 12 entirely new entries) as HYG v3.7. I will close the issue soon if no other related problems occur.

**Closed** 2023-09-26 19:56 UTC
