### ISSUE TITLE
Please specify license

### ISSUE THREAD

**Issue by naugtur** [astronexus/HYG-Database#8] opened 2017-01-06 22:25 UTC
Hi,

I'm considering using this data to create some fun virtual reality space travel toy, hopefully not limited to my private use. 

I would like to know what is the license for your data. Since you're publishing it already, you probably want to choose one of the CC licenses, unless the original sources force otherwise.

**Comment by kbahey** [comment] 2019-03-03 03:55
Duplicate of #11, but no reply so far.

**Comment by meshula** [comment] 2019-03-04 00:10
The license (https://creativecommons.org/licenses/by-sa/2.5/) is on the database's website (http://www.astronexus.com/node/9)

**Comment by kbahey** [comment] 2019-03-06 20:48
That is one level of unnecessary indirection, and hence people asking about it.

 It should be as a separate LICENSE file in the repo, or at least in the README file, explicitly stated.

**Comment by meshula** [comment] 2019-03-06 21:16
I agree, I had to search quite a bit to discover that link, so I thought I should share the link for other users of the library, since this repo hasn't been active for some time.

**Comment by brandelune** [comment] 2019-03-07 08:49
It should be possible to modify the status and create a PR to have the data included in the main repository.

**Comment by kbahey** [comment] 2019-03-07 16:16
I don't want to sound like I am belittling the effort of someone who has worked hard for years (almost 2 decades) maintaining astronomical data, refining it, and providing it to others. 

However, the fact that his project is dormant has hindered its adoption.

That is why planetariums, such as KStars and Cartes du Ciels have moved on to [Open NGC](https://github.com/mattiaverga/OpenNGC). I ended up using the OpenNGC data as well for [OnStep's Smart Hand Controller](https://github.com/hjd1964/OnStep/tree/Alpha/addons/St4Serial/SmartHandController) because of the license.

It is a pity, since Open NGC does not have the Caldwell objects, which is nice to have.

**Comment by astronexus** [comment] 2019-03-07 17:04
I have updated the README with the current license.

**Closed by astronexus** 2019-03-07 17:04 UTC
